services:
  web:
    container_name: pokedex-next-frontend-development
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
      args:
        NODE_VERSION: '24.12.0'
    image: pokedex-next-frontend:development
    env_file:
      - ../../.env.local
    ports:
      - '3000:3000'
    volumes:
      - ../..:/app
      - /app/node_modules
      - /app/.next
