import type { Metadata } from 'next';
import { Press_Start_2P, Rubik, VT323 } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import ThemeProvider from '~/components/providers/ThemeProvider/ThemeProvider';
import { DEFAULT_LOCALE } from '~/constants/locales';
import '~/styles/tokens.css';
import '~/styles/global.scss';

const pressStart2P = Press_Start_2P({
  variable: '--font-display',
  weight: '400',
  subsets: ['latin'],
});

const rubik = Rubik({
  variable: '--font-body',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const vt323 = VT323({
  variable: '--font-mono',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/favicon/favicon-96x96.png',
        sizes: '96x96',
        type: 'image/png',
      },
      { url: '/favicon/favicon.svg', type: 'image/svg+xml' },
    ],
    shortcut: '/favicon/favicon.ico',
    apple: '/favicon/apple-touch-icon.png',
  },
  manifest: '/favicon/site.webmanifest',
};

const RootLayout = ({ children }: LayoutProps<'/'>) => {
  return (
    <html
      lang={DEFAULT_LOCALE}
      suppressHydrationWarning
      className={`${pressStart2P.variable} ${rubik.variable} ${vt323.variable}`}
    >
      <body>
        <ThemeProvider>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
